# Generated by Django 3.2.23 on 2024-01-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to='cats/images/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
